name: Regression CI
on:
  push:
    branches:
      - main
      - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Regression job performs installation of gdk as our customers would. Runs our UAT suite for
  # each matrix permutation to detect regression failures.
  regression:
    strategy:
      max-parallel: 6
      matrix:
        gdk-version: [ HEAD, v1.6.0, v1.5.0]
        python-version: [3.7, 3.8, 3.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    name: Regression of GDK ${{ matrix.gdk-version == 'HEAD' && '' || matrix.gdk-version }} on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.gdk-version == 'HEAD' && github.ref || matrix.gdk-version }}
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CLI and dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip
          # Perform clean install without test dependencies to ensure none of test dependencies
          # have been used in the gdk codebase.
          pip install .
          gdk --help
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.GDK_WORKFLOW_AWS_ROLE}}
          aws-region: us-east-1
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: corretto
      - name: Get Latest UATs
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Run UATs
        run: |
          pip install -r test-requirements.txt
          behave -v uat/ -D gdk-debug=true -D target-version=${{ matrix.gdk-version }}
